import { arrArrayFrom, arrBool, arrInt, arrObjectFrom, arrString } from '../support/arr.js'
import { Invoice } from './invoice.js'
import { InvoiceCustomer } from './invoice-customer.js'
import { InvoiceLineItem } from './invoice-line-item.js'

type Raw = Record<string, unknown>

export class RecurringInvoice {
  constructor(
    public readonly id?: number,
    public readonly status?: string,
    public readonly recurrenceSchedule?: string,
    public readonly paymentTerms?: string,
    public readonly startDate?: string,
    public readonly endDate?: string,
    public readonly nextRunDate?: string,
    public readonly lastRunDate?: string,
    // Present on the list-summary shape; the full shape nests this under `customer`.
    public readonly customerName?: string,
    public readonly thankYouNote?: string,
    public readonly customer: InvoiceCustomer = new InvoiceCustomer(),
    public readonly items: InvoiceLineItem[] = [],
    public readonly upcomingRunDates: string[] = [],
    // The most recent invoices generated by this template.
    public readonly invoices: Invoice[] = [],
    // Copied onto every invoice this template generates.
    public readonly coverFeeRequired: boolean = false,
  ) {}

  static fromRaw(data: Raw): RecurringInvoice {
    const runDates = data['upcoming_run_dates']

    return new RecurringInvoice(
      arrInt(data, 'id'),
      arrString(data, 'status'),
      arrString(data, 'recurrence_schedule'),
      arrString(data, 'payment_terms'),
      arrString(data, 'start_date'),
      arrString(data, 'end_date'),
      arrString(data, 'next_run_date'),
      arrString(data, 'last_run_date'),
      arrString(data, 'customer_name'),
      arrString(data, 'thank_you_note'),
      InvoiceCustomer.fromRaw(arrObjectFrom(data, ['customer'])),
      arrArrayFrom(data, 'items').map(InvoiceLineItem.fromRaw),
      Array.isArray(runDates) ? runDates.map((d) => String(d)) : [],
      arrArrayFrom(data, 'invoices').map(Invoice.fromRaw),
      arrBool(data, 'cover_fee_required'),
    )
  }
}
